### ISSUE TITLE
A google chrome extension that replaces the new tab with a text editor

### ISSUE THREAD

**Issue by BosEriko** [egoist/sponsors#3]
Preferably with an option to enable VIM hotkeys

**Comment by BosEriko** [comment]
I'm not a sponsor, though. 😂 
Just thought that you might see this useful or something. Who knows, a chrome OS user might use it often. (I know I will)

**Comment by egoist** [comment]
This issue was moved to https://egoist.chat/t/a-google-chrome-extension-that-replaces-the-new-tab-with-a-text-editor/24
